apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-reencrypt-ssl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-demo-app-route-reencrypt-ssl
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-demo-httpd
        ports:
        - containerPort: 443
          protocol: TCP