apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-basic
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-demo-app-route-basic
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world:develop
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-balance
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-demo-app-route-balance
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world:develop
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-edge-ssl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-demo-app-route-edge-ssl
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world:develop
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-demo-app-route-reencrypt-ssl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: f5-demo-app-route-reencrypt-ssl
    spec:
      containers:
      - name: service_name
          value: f5-demo-app-route-reencrypt-ssl
        image: f5devcentral/f5-demo-httpd
        imagePullPolicy: Always
        name: f5-demo-app-route-reencrypt-ssl
        ports:
        - containerPort: 443
          protocol: TCP