apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-reencrypt
  namespace: f5demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: f5-demo-app-route-reencrypt
    spec:
      containers:
      - name: f5-demo-app-route
        image: chen23/f5-demo-app:openshift
        ports:
        - containerPort: 443
          protocol: TCP