apiVersion: v1
kind: Service
metadata:
    name: f5-demo-app-route-basic
    labels:
        name: f5-demo-app-route-basic
    namespace: f5demo
spec:
    type: ClusterIP
    ports:
        -
            port: 8080
            targetPort: 8080
    selector:
        app: f5-demo-app-route